---
zabbix_version: "6.0"
zabbix_repo_url: "https://repo.zabbix.com/zabbix/6.0/debian/pool/main/z/zabbix-release/zabbix-release_latest_6.0+debian10_all.deb"
zabbix_server_conf_path: "/etc/zabbix/zabbix_server.conf"
zabbix_allow_unsupported_db: 1
