---
- name: Cargar variables espec√≠ficas por OS
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "default.yml"

- name: Instalar Zabbix Agent
  apt:
    name: zabbix-agent
    state: present

- name: Habilitar e iniciar Zabbix Agent
  service:
    name: zabbix-agent
    state: restarted
    enabled: yes
